packaging_format = 2

id = "lxd-dashboard"
name = "LXD Dashboard"
description.en = "Makes it easy for you to take control of your LXD based infrastructure"
description.fr = "Vous permet de prendre facilement le contrôle de votre infrastructure basée sur LXD"

version = ".3.8.0~ynh1"

maintainers = ["yalh76"]

[upstream]
license = "AGPL-3.0-or-later"
website = "https://lxdware.com"
code = "https://github.com/lxdware/lxd-dashboard"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/lxd-dashboard"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]
        [resources.sources.main]
        url = "https://github.com/lxdware/lxd-dashboard/archive/refs/tags/v.3.8.0.tar.gz"
        sha256 = "4884774cf69600e17bb107eab79767499ffd8444c2be0b443f15c4b8d4f175cb"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["backups", "data/lxd"]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, php8.2-curl php8.2-mysql"

    [resources.database]
    type = "mysql"
